### ISSUE TITLE
improve and expand documentation on using secrets/certs in KMS for timestamp-server

### ISSUE THREAD

**Issue by dmitris** [sigstore/timestamp-authority#421]
**Description**

The current documentation on using KMS to store certificates https://github.com/sigstore/timestamp-authority#cloud-kms is somewhat unclear on what needs to be done, and possibly less general and with emphasis on GCP and Tink.  It makes a bit an impression of "leaving the details as an exercise" for the user 😄  - "look at this code [`fetch_tsa_certs.go`] and figure out how to adapt it for your use-case".

**Comment by haydentherapper** [comment]
For context, the service was designed originally to be run on GCP where the root was hosted with GCP CA Service, which is why you'll see that `fetch_tsa_certs.go` hardcodes certain resource expectations. As another way to deploy the service to minimize calls to KMS, Tink provides a secure way to use an in-memory key that is encrypted with a KMS key so that the unencrypted key is never on disk.

The KMS library supports GCP, AWS, Azure, and Hashicorp Vault. Tink supports GCP, AWS, and Vault. Once you have the CA certificate chain, any of these cloud providers can be used.

Roughly, you'll need to do the following to run the service with KMS:
* Get a certificate chain where the leaf certificate certifies the KMS public key. The chain must start with a root and end with a leaf certificate which follows RFC3161 (namely, the timestamping EKU is set to critical), with any number of intermediate CA certificates.
  * There will be a lot of variations for how this is fetched - Your root could be hosted offline, in an HSM, in GCP CA Service, in AWS CA Service, as a KMS key, etc. Same with the intermediates.
  * `fetch_ca_certs` presents one suggested deployment, where the root is a hosted CA in GCP CA Service and the intermediate certificate is generated from a KMS key denoted to be for an intermediate CA certificate. It also supports a Tink keyset, which is a raw key encrypted with a KMS key and is loaded into memory on service startup.
  * Open to PRs to create more scripts to fetch certificate chains.
* Deploy the timestamp authority following the readme: "Set `--timestamp-signer=kms`, provide the path to the chain with `--certificate-chain-path`, and the KMS key with `--kms-key-resource`. The key should be prefixed with either `gcpkms://`, `azurekms://`, `awskms://`, or `hashivault://`"
  * If using a Tink keyset, "set `--timestamp-signer=tink`, `--tink-key-resource=<path-to-kms-key>`, and
`--tink-keyset-path=enc-keyset.cfg`. The key resource should be prefixed with either `gcp-kms://`, `aws-kms://`, or `hcvault://`. If using Vault, you may also set `--tink-hcvault-token`. Provide the path to the chain with `--certificate-chain-path`."

@malancas Did you have anything to add from your experience? 

We can update the documentation with this info.

**Comment by malancas** [comment]
@haydentherapper that about summarizes everything up. My one suggestion to users who want to run a TSA is to confirm their certificate chain can be successfully verified with [VerifyCertChain](https://github.com/sigstore/timestamp-authority/blob/main/pkg/x509/x509.go#L35) to prevent issues when trying to start the server.
